version: '3.4'

services:
  dashboard:
    build: .
    image: "${REGISTRY_NAME}devclubiitd/all_in_one_party_server:0.1"
    ports:
      - ${PORT}:${PORT}
    healthcheck:
      test: ["CMD", "curl", "http://localhost:${PORT}/healthz"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: "unless-stopped" 
    networks:
      - "internal"
      - "reverseproxy"
    environment:
      - VIRTUAL_HOST
    
networks:
  reverseproxy:
    external:
      name: "reverseproxy"
  internal: